import requests

# URL do endpoint da API de importação de dados
url = "https://maestro.dadosfera.ai/upload/jsonl"

# Headers da requisição
headers = {
    'Authorization': 'Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6InByZC9yb290L2p3dC9lYzUyMSJ9.eyJ1c2VyX2lkIjoiNjVjYWY4YWQtNmMzNy00MzE3LTk1ZDAtYjA2MWEwNTFhNzY4IiwidXNlcm5hbWUiOiJtaWthZWwuYWtpaGl0dG85OEBnbWFpbC5jb20iLCJjdXN0b21lcl9pZCI6ImVkMjM5MTM1LWVlMjMtNGQ1Zi1iY2E5LTljYjY3NTllN2RiMyIsImN1c3RvbWVyX25hbWUiOiJ0cmVpbmFtZW50b3MiLCJjdXN0b21lcl90aWVyIjoiQkFTSUMiLCJwZXJtaXNzaW9ucyI6WzcsMTMsMzEsMTEsMjMsMjksMzcsMjUsMTldLCJjb2duaXRvX2FjY2Vzc190b2tlbiI6ImV5SnJhV1FpT2lJMmFXOUxZWFZ4TkhkQ01HUTJkRGhPVmpKVlVFMVNYQzlZYzBaT1NqWklVazR6ZWx3dksyMUplRzFMU0RBOUlpd2lZV3huSWpvaVVsTXlOVFlpZlEuZXlKemRXSWlPaUkyTldOaFpqaGhaQzAyWXpNM0xUUXpNVGN0T1RWa01DMWlNRFl4WVRBMU1XRTNOamdpTENKcGMzTWlPaUpvZEhSd2N6cGNMMXd2WTI5bmJtbDBieTFwWkhBdWRYTXRaV0Z6ZEMweExtRnRZWHB2Ym1GM2N5NWpiMjFjTDNWekxXVmhjM1F0TVY5TmNtVjZjM2M1VTI0aUxDSmpiR2xsYm5SZmFXUWlPaUkwY1hZeU5XeGpaSFZoTkhZNWRHUXhhREp2TVdFNGN6UjJNeUlzSW05eWFXZHBibDlxZEdraU9pSmlZelkzT0RNME5TMHpNVGRsTFRSaE9Ea3RZVFkwTnkwMU1UaGtPRE01WTJKaU5EUWlMQ0psZG1WdWRGOXBaQ0k2SW1Wak9XRTVZall4TFRJNU0yRXROR1F4T0MxaE5HTXhMV016WkdVMk9ERmpORGN4TlNJc0luUnZhMlZ1WDNWelpTSTZJbUZqWTJWemN5SXNJbk5qYjNCbElqb2lZWGR6TG1OdloyNXBkRzh1YzJsbmJtbHVMblZ6WlhJdVlXUnRhVzRpTENKaGRYUm9YM1JwYldVaU9qRTNNVFV6TmpreU56UXNJbVY0Y0NJNk1UY3hOVE0zTVRBM05Dd2lhV0YwSWpveE56RTFNelk1TWpjMExDSnFkR2tpT2lJNFlqTTVaakl5WXkwNU5qUTVMVFE1TmpjdFlUQXpOQzAzTXprME5UUTNaV1ZoTldJaUxDSjFjMlZ5Ym1GdFpTSTZJbTFwYTJGbGJDNWhhMmxvYVhSMGJ6azRRR2R0WVdsc0xtTnZiU0o5LlJmQzU2UGt5UWtzd3FuZC1hQS03Z3FfZjl6eTZ3dXFSTTQtT0lmZWc3MnE1Umdkd3NYT2tDenhuTzdxR3J4by1nVU93UVNlcktOcU9MMWx0NU5SbEhKRFZmSVpJZk9yd0hUS2Y0dTZlajZfV3FGN2EtbWVNb2k4dGl2TzJnWHpZQko5dTN3RjR3bm0ybzBST2dNbEFMdVEtUWU3LWNwYW9rMGZGMG8yaE5hT0pveXFVaXNZU2N1RjRWNXljeWtrUFBONnlwUEpTbFV4TzJ5QlZWQ3BEeVZBZ1V3bWEzT0ctaHdXdFp5WXlVbzRQTEtuRVpjTEdaa2ZwVFBmYTJzUG5DR2VzYk9EdlFYY3hNN0ZTMVZIVDAwcHJxNUxwQVhidkk3RFVSeFZMZ1dKeFY0X0pXWHprNmZRbDgyU2RrY00xUVlyR09tUlpHYk5BWXQwVzFNUXZWUSIsInRva2VuX3VzZSI6ImFjY2VzcyIsImV4cCI6MTcxNTM3MTA0NCwiaWF0IjoxNzE1MzY5Mjc0fQ.ABi_JJwe3Z6C8DhcRPcTL4JLJ9kQvSo_m-jLQcwvJfbl4pm37gYsfuT9o59psBWtAIvuSHxzn-pFxqx_n2aP12VgAZSqcTdWDBNhwiR2DtMLl1IijATLoKljuaTb3lysaoqE-X-S-RqgQYS9nNVThJyt-I7TC76utxpxcIgorgpdFPUI',
  # Substitua YOUR_ACCESS_TOKEN pelo seu token de acesso
    'Content-Type': 'application/json'
}

# Caminho para o arquivo JSON que será carregado
file_path = 'corpus-simple.jsonl'

# Leitura do arquivo JSON
with open(file_path, 'r') as file:
    json_data = file.read()

# Realização do POST request
response = requests.post(url, headers=headers, data=json_data)

# Verificação da resposta
if response.status_code == 200:
    print("Arquivo carregado com sucesso.")
else:
    print(f"Falha no carregamento. Status code: {response.status_code}")
    print("Resposta:", response.text)